[package]
name = "zenith-transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "0.52.0", features = ["lazy", "parquet", "timezones"] }
deunicode = "1.6.2"
candle-core = { version = "0.9.2", features = ["cuda"] }
candle-nn = { version = "0.9.2", features = ["cuda"] }
rand = "0.9.2"
anyhow = "1.0.100"
env_logger = "0.11.8"
clap = { version = "4.5.57", features = ["derive"] }
log = "0.4.29"